### PR TITLE
update + delete + backend auth added

### PR DESCRIPTION
**Pull request by saksham-kumar-14**
#5 #6 
I added edit and delete options for the results table + backend authentication for the admin.

# **Process**
### For edit and delete options ,
I made 2 server endpoints for performing the tasks
Screenshot 2024-12-05 at 10 06 25 PM
Preview of the results page when user is authenticated as admin
<br>
Screenshot 2024-12-05 at 10 07 01 PM
Preview of the results page when edit option is selected
<br>

Screenshot 2024-12-05 at 10 07 45 PM
Preview of the results page when user is not authenticated as admin
<br>

### For backend authentication,
I made a server endpoint for admin authentication. Moreover, the endpoint returns a jsonwebtoken which is stored in the localstorage. Therefore, authentication through this token is also possible

### CODE REVIEW

**Comment by Majestic9169** [comment]
please rebase with the added `.gitignore` and remove node_modules

**Comment by Majestic9169** [comment]
looks good though, I'll review once you remove the node_modules

**Comment by saksham-kumar-14** [comment]
@Majestic9169 done

**Review by Majestic9169 — COMMENTED** [review]
First of all you can directly merge the main branch with your feature branch, that would clean up everything directly and make reviewing easier for me, since currently it shows you manually deleting all node_modules which creates huge diffs to review

honestly very good pr, I just have some style changes to request. could you please shfit the delete column to the right instead, and use icons instead of text for those columns. that way you won't need headers for those 2 columns either

2nd add a confirmation when someone clicks on delete, it is far too easy to delete an entry currently

**Comment by Majestic9169** [comment]
please merge the main branch with your feature branch, then go through the changes requested

good work!

**Comment by saksham-kumar-14** [comment]
# Changes done

1. a delete confirmation box appears now
Screenshot 2024-12-16 at 3 52 11 AM
<br><br>
2. icons are used + delete button is aligned to the right side
Screenshot 2024-12-16 at 3 51 47 AM
<br><br>
3. main branch is merged with the feature branch

**Comment by Majestic9169** [comment]
Great!

Merging

**Pull request merged**
