### PR TITLE
fix: Changes for authentication

### PR DESCRIPTION
**Pull request by SGI-CAPP-AT2**
## CHANGE 1
Changed way of authentication after login

Before change:
- After logging in to keep logged in we've used a stored boolean value to make sure user has logged in
- This was creating problem when we change password user was logged in even if wrong old password has been used to login

Now:
- Instead of boolean we're now using password to keep user logged in 
- It makes sure user has been logged in with correct password

## CHANGE 2

added gitignore to ignore changes under node_modules

- All files under node_modules was being tracked
- It was making harder to track real changes
- git add . was not working

Fixed by adding both node_modules to gitignore

### CODE REVIEW

**Comment by SGI-CAPP-AT2** [comment]
@Majestic9169 You can review this PR.
If you need any changes, please mention me

**Comment by Majestic9169** [comment]
please rebase with the added `.gitignore` and remove node_modules

i'll review after that

**Comment by SGI-CAPP-AT2** [comment]
@Majestic9169 done!

**Review by Majestic9169 — CHANGES_REQUESTED** [review]
currently we don't have a password change endpoint, so the issue of storing authentication boolean, or password itself doesn't really arise. That's fine though, no worries

However storing our authenticated state in localStorage is not a good idea. We should probably use cookies. And if we go that far, we could just set up JWT authentication with a login endpoint in the backend. 

Do try to implement JWT auth, current changes are not really beneficial to the project

**Comment by Majestic9169** [comment]
Pr #16 closed these issues, please work on something else

**Pull request closed without merging**
